%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /oxa-181_single_events020518b.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/03/03 20:27:42

clc, clear, close all
%% Import the data
[~, ~, raw] = xlsread('/oxa-181_single_events020518b.xlsx','Sheet1');
raw = raw(:,[3,6,8,11,14,17,20,23,end]);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
model = data(:,1);
model = model(10:291);
Ev36 = data(:,2);
Ev36 = Ev36(2:end);
Ev28 = data(:,3);
Ev28 = Ev28(2:end);
Ev12 = data(:,4);
Ev12 = Ev12(2:end);
Ev1 = data(:,5);
Ev1 = Ev1(2:end);
Ev16 = data(:,6);
Ev16 = Ev16(2:end);
Ev7 = data(:,7);
Ev7 = Ev7(2:end);
Ev33 = data(:,8);
Ev33 = Ev33(2:end);
Ev19 = data(:,9);
Ev19 = Ev19(2:end);

%% Clear temporary variables
clearvars data raw R;

%% Sample Calculation for Event 1:
d = dtw_pairwise_oxa(model,Ev1);